### ISSUE TITLE
Regression in TestNG in 1.8.1.Final

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#584]
##### Issue Overview

@lprimak reported that TestNG tests were failing under 1.8.1.Final. We need a reproducer to determine what the cause is.

##### Expected Behaviour
No changes were made in the TestNG layer, so there should be no changes for those unit tests

##### Current Behaviour
A regression has been reported.

##### Steps To Reproduce
1. TODO
2. TODO

**Comment by lprimak** [comment]
The issue was binary incompatibility between 1.8.0.Final and 1.8.1.Final when it comes to Jakarta protocol JARs.

If you don't upgrade implementation-specific JARs to depend on 1.8.1, but upgrade core to 1.8.1, it'll fail, which is what happened.
Solution is to release 1.9.x next, because 1.8.1 is binary-incompatible with 1.8.0 which violates semantic versioning.
