### ISSUE TITLE
Jakarta Protocols 1.9.0 are missing

### ISSUE THREAD

**Issue by lprimak** [arquillian/arquillian-core#592]
Arquillian core 1.9.0 has been released.
However, Jakarta protocol JARs are sill 1.8.1

Please release 1.9.0 versions of these JARs.

Thank you

**Comment by jamezp** [comment]
Why do the Jakarta protocols need a new release? They are a separate project with a separate BOM.

**Comment by lprimak** [comment]
If that was true, the protocol version would be 1.0, not 1.8.1 This is not a coincidence :)
The "new" BOM was "introduced" in 1.8.1 (a minor version) which breaks semantic versioning.

In any case, if the protocols versions are going to mirror Core versions, their versions need to be consistent.
If not, they can't be confusing like this, i.e. they should start with 1.0, not 1.8.x

**Comment by hantsy** [comment]
I encountered the same issue when upgrading to Aruqillian 1.9.0.Final

```bash 
Some problems were encountered while processing the POMs:
Error:  'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet-jakarta:jar is missing
```

**Comment by hantsy** [comment]
> Why do the Jakarta protocols need a new release? They are a separate project with a separate BOM.

I was using the BOM in my projects to manage the dependency versions.

```xml
<dependency>
    <groupId>org.jboss.arquillian</groupId>
    <artifactId>arquillian-bom</artifactId>
    <version>${arquillian-bom.version}</version>
    <scope>import</scope>
    <type>pom</type>
</dependency>
```

**Comment by starksm64** [comment]
So as of the 1.9.0.Final release of arquillian-core, arquillian-jarkarta is not in the bom, and neither are the shrinkwrap dependencies. Only arquillian-core artifacts are in there.

The 1.8.1.Final release of the does include its own bom, but since it refers to the 1.7.1.Final bom for arquillian-core, it should be updated.

We should really just give it a version number like 10.0.0.Final to refer to the versions of the Jakarta APIs.

This is the type of bom import that needs to be done as of arquillian-core 1.9.0.Final:

```
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.10.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.shrinkwrap.resolver</groupId>
                <artifactId>shrinkwrap-resolver-bom</artifactId>
                <version>${version.shrinkwrap}</version>
                <scope>test</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.jboss.shrinkwrap.resolver</groupId>
                <artifactId>shrinkwrap-resolver-depchain</artifactId>
                <version>${version.shrinkwrap}</version>
                <type>pom</type>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>${version.arquillian_core}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian.jakarta</groupId>
                <artifactId>arquillian-jakarta-bom</artifactId>
                <version>${version.arquillian_jakarta}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by lprimak** [comment]
Yup. 10.0.0 should work great!

**Comment by hantsy** [comment]
> Yup. 10.0.0 should work great!

@starksm64 It is OK to align the Jakarta variant to the Jakarta EE version. 

But another issue we will face is that the servlet protocol is versioned in *aquillian.xml*, thus means we will use a general `Servlet` as protocol and discard the version number. Because the servlet version is aligned with Jakarta EE version by default.

* Jakarta EE 9 - Servlet 5
* Jakarta EE 10 - Servlet 6

**Comment by starksm64** [comment]
10.0.0.Final is released.
https://github.com/arquillian/arquillian-jakarta/releases/tag/10.0.0.Final
